//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT

@_spi(SotoInternal) import SotoCore

// MARK: - Enums

/// Lambda function architecture
@available(LambdaSwift 2.0, *)
public enum LambdaArchitecture: String, Codable, Sendable {
    case x86_64 = "x86_64"
    case arm64 = "arm64"
}

/// Lambda function runtime
@available(LambdaSwift 2.0, *)
public enum LambdaRuntime: String, Codable, Sendable {
    case providedAl2023 = "provided.al2023"
    case providedAl2 = "provided.al2"
}

/// Lambda function packaging type
@available(LambdaSwift 2.0, *)
public enum LambdaPackageType: String, Codable, Sendable {
    case zip = "Zip"
    case image = "Image"
}

/// Function URL auth type
@available(LambdaSwift 2.0, *)
public enum FunctionUrlAuthType: String, Codable, Sendable {
    case awsIam = "AWS_IAM"
    case none = "NONE"
}

// MARK: - GetFunction

/// Request for GetFunction operation
@available(LambdaSwift 2.0, *)
public struct GetFunctionRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String

    public init(functionName: String) {
        self.functionName = functionName
    }

    public func encode(to encoder: Encoder) throws {
        _ = encoder.container(keyedBy: CodingKeys.self)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.functionName, key: "FunctionName")
    }

    private enum CodingKeys: CodingKey {}
}

/// Response for GetFunction operation
@available(LambdaSwift 2.0, *)
public struct GetFunctionResponse: AWSDecodableShape, Sendable {
    /// The configuration of the function.
    public let configuration: FunctionConfiguration?
    /// The deployment package of the function.
    public let code: FunctionCodeLocation?

    private enum CodingKeys: String, CodingKey {
        case configuration = "Configuration"
        case code = "Code"
    }
}

/// Function configuration details
@available(LambdaSwift 2.0, *)
public struct FunctionConfiguration: Codable, Sendable {
    /// The name of the function.
    public let functionName: String?
    /// The function's Amazon Resource Name (ARN).
    public let functionArn: String?
    /// The runtime environment.
    public let runtime: String?
    /// The function's execution role.
    public let role: String?
    /// The function's handler.
    public let handler: String?
    /// The size of the function's deployment package, in bytes.
    public let codeSize: Int64?
    /// The function's description.
    public let description: String?
    /// The amount of time in seconds that Lambda allows a function to run before stopping it.
    public let timeout: Int?
    /// The amount of memory available to the function at runtime.
    public let memorySize: Int?
    /// The latest updated date.
    public let lastModified: String?
    /// The SHA256 hash of the deployment package.
    public let codeSha256: String?
    /// The version of the Lambda function.
    public let version: String?
    /// The function's state.
    public let state: String?
    /// The reason for the function's current state.
    public let stateReason: String?
    /// The instruction set architecture.
    public let architectures: [String]?

    private enum CodingKeys: String, CodingKey {
        case functionName = "FunctionName"
        case functionArn = "FunctionArn"
        case runtime = "Runtime"
        case role = "Role"
        case handler = "Handler"
        case codeSize = "CodeSize"
        case description = "Description"
        case timeout = "Timeout"
        case memorySize = "MemorySize"
        case lastModified = "LastModified"
        case codeSha256 = "CodeSha256"
        case version = "Version"
        case state = "State"
        case stateReason = "StateReason"
        case architectures = "Architectures"
    }
}

/// Function code location details
@available(LambdaSwift 2.0, *)
public struct FunctionCodeLocation: Codable, Sendable {
    /// The service that hosts the deployment package.
    public let repositoryType: String?
    /// A presigned URL to download the deployment package.
    public let location: String?

    private enum CodingKeys: String, CodingKey {
        case repositoryType = "RepositoryType"
        case location = "Location"
    }
}

// MARK: - CreateFunction

/// Function code for CreateFunction
@available(LambdaSwift 2.0, *)
public struct FunctionCode: Codable, Sendable {
    /// The base64-encoded contents of the deployment package.
    public let zipFile: String?
    /// An Amazon S3 bucket in the same AWS Region as your function.
    public let s3Bucket: String?
    /// The Amazon S3 key of the deployment package.
    public let s3Key: String?

    public init(zipFile: String? = nil, s3Bucket: String? = nil, s3Key: String? = nil) {
        self.zipFile = zipFile
        self.s3Bucket = s3Bucket
        self.s3Key = s3Key
    }

    private enum CodingKeys: String, CodingKey {
        case zipFile = "ZipFile"
        case s3Bucket = "S3Bucket"
        case s3Key = "S3Key"
    }
}

/// Request for CreateFunction operation
@available(LambdaSwift 2.0, *)
public struct CreateFunctionRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String
    /// The Amazon Resource Name (ARN) of the function's execution role.
    public let role: String
    /// The identifier of the function's runtime.
    public let runtime: LambdaRuntime
    /// The name of the method within your code that Lambda calls to run your function.
    public let handler: String
    /// The code for the function.
    public let code: FunctionCode
    /// A description of the function.
    public let description: String?
    /// The amount of time (in seconds) that Lambda allows a function to run before stopping it.
    public let timeout: Int?
    /// The amount of memory available to the function at runtime.
    public let memorySize: Int?
    /// The instruction set architecture.
    public let architectures: [LambdaArchitecture]?
    /// The type of deployment package.
    public let packageType: LambdaPackageType?

    public init(
        functionName: String,
        role: String,
        runtime: LambdaRuntime,
        handler: String,
        code: FunctionCode,
        description: String? = nil,
        timeout: Int? = nil,
        memorySize: Int? = nil,
        architectures: [LambdaArchitecture]? = nil,
        packageType: LambdaPackageType? = nil
    ) {
        self.functionName = functionName
        self.role = role
        self.runtime = runtime
        self.handler = handler
        self.code = code
        self.description = description
        self.timeout = timeout
        self.memorySize = memorySize
        self.architectures = architectures
        self.packageType = packageType
    }

    private enum CodingKeys: String, CodingKey {
        case functionName = "FunctionName"
        case role = "Role"
        case runtime = "Runtime"
        case handler = "Handler"
        case code = "Code"
        case description = "Description"
        case timeout = "Timeout"
        case memorySize = "MemorySize"
        case architectures = "Architectures"
        case packageType = "PackageType"
    }
}

/// Response for CreateFunction operation
@available(LambdaSwift 2.0, *)
public struct CreateFunctionResponse: AWSDecodableShape, Sendable {
    /// The name of the function.
    public let functionName: String?
    /// The function's Amazon Resource Name (ARN).
    public let functionArn: String?
    /// The runtime environment.
    public let runtime: String?
    /// The function's execution role.
    public let role: String?
    /// The function's handler.
    public let handler: String?
    /// The size of the function's deployment package, in bytes.
    public let codeSize: Int64?
    /// The function's description.
    public let description: String?
    /// The function's state.
    public let state: String?
    /// The instruction set architecture.
    public let architectures: [String]?
    /// The version of the Lambda function.
    public let version: String?

    private enum CodingKeys: String, CodingKey {
        case functionName = "FunctionName"
        case functionArn = "FunctionArn"
        case runtime = "Runtime"
        case role = "Role"
        case handler = "Handler"
        case codeSize = "CodeSize"
        case description = "Description"
        case state = "State"
        case architectures = "Architectures"
        case version = "Version"
    }
}

// MARK: - UpdateFunctionCode

/// Request for UpdateFunctionCode operation
@available(LambdaSwift 2.0, *)
public struct UpdateFunctionCodeRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String
    /// The base64-encoded contents of the deployment package.
    public let zipFile: String?
    /// An Amazon S3 bucket in the same AWS Region as your function.
    public let s3Bucket: String?
    /// The Amazon S3 key of the deployment package.
    public let s3Key: String?
    /// The instruction set architecture.
    public let architectures: [LambdaArchitecture]?

    public init(
        functionName: String,
        zipFile: String? = nil,
        s3Bucket: String? = nil,
        s3Key: String? = nil,
        architectures: [LambdaArchitecture]? = nil
    ) {
        self.functionName = functionName
        self.zipFile = zipFile
        self.s3Bucket = s3Bucket
        self.s3Key = s3Key
        self.architectures = architectures
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.zipFile, forKey: .zipFile)
        try container.encodeIfPresent(self.s3Bucket, forKey: .s3Bucket)
        try container.encodeIfPresent(self.s3Key, forKey: .s3Key)
        try container.encodeIfPresent(self.architectures, forKey: .architectures)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.functionName, key: "FunctionName")
    }

    private enum CodingKeys: String, CodingKey {
        case zipFile = "ZipFile"
        case s3Bucket = "S3Bucket"
        case s3Key = "S3Key"
        case architectures = "Architectures"
    }
}

/// Response for UpdateFunctionCode operation
@available(LambdaSwift 2.0, *)
public struct UpdateFunctionCodeResponse: AWSDecodableShape, Sendable {
    /// The name of the function.
    public let functionName: String?
    /// The function's Amazon Resource Name (ARN).
    public let functionArn: String?
    /// The runtime environment.
    public let runtime: String?
    /// The function's execution role.
    public let role: String?
    /// The function's handler.
    public let handler: String?
    /// The size of the function's deployment package, in bytes.
    public let codeSize: Int64?
    /// The function's state.
    public let state: String?
    /// The instruction set architecture.
    public let architectures: [String]?
    /// The version of the Lambda function.
    public let version: String?

    private enum CodingKeys: String, CodingKey {
        case functionName = "FunctionName"
        case functionArn = "FunctionArn"
        case runtime = "Runtime"
        case role = "Role"
        case handler = "Handler"
        case codeSize = "CodeSize"
        case state = "State"
        case architectures = "Architectures"
        case version = "Version"
    }
}

// MARK: - DeleteFunction

/// Request for DeleteFunction operation
@available(LambdaSwift 2.0, *)
public struct DeleteFunctionRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String

    public init(functionName: String) {
        self.functionName = functionName
    }

    public func encode(to encoder: Encoder) throws {
        _ = encoder.container(keyedBy: CodingKeys.self)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.functionName, key: "FunctionName")
    }

    private enum CodingKeys: CodingKey {}
}

// MARK: - CreateFunctionUrlConfig

/// Request for CreateFunctionUrlConfig operation
@available(LambdaSwift 2.0, *)
public struct CreateFunctionUrlConfigRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String
    /// The type of authentication that your function URL uses.
    public let authType: FunctionUrlAuthType

    public init(functionName: String, authType: FunctionUrlAuthType) {
        self.functionName = functionName
        self.authType = authType
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.authType, forKey: .authType)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.functionName, key: "FunctionName")
    }

    private enum CodingKeys: String, CodingKey {
        case authType = "AuthType"
    }
}

/// Response for CreateFunctionUrlConfig operation
@available(LambdaSwift 2.0, *)
public struct CreateFunctionUrlConfigResponse: AWSDecodableShape, Sendable {
    /// The HTTP URL endpoint for the function.
    public let functionUrl: String?
    /// The Amazon Resource Name (ARN) of the function.
    public let functionArn: String?
    /// The type of authentication.
    public let authType: String?
    /// When the function URL was created.
    public let creationTime: String?

    private enum CodingKeys: String, CodingKey {
        case functionUrl = "FunctionUrl"
        case functionArn = "FunctionArn"
        case authType = "AuthType"
        case creationTime = "CreationTime"
    }
}

// MARK: - DeleteFunctionUrlConfig

/// Request for DeleteFunctionUrlConfig operation
@available(LambdaSwift 2.0, *)
public struct DeleteFunctionUrlConfigRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String

    public init(functionName: String) {
        self.functionName = functionName
    }

    public func encode(to encoder: Encoder) throws {
        _ = encoder.container(keyedBy: CodingKeys.self)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.functionName, key: "FunctionName")
    }

    private enum CodingKeys: CodingKey {}
}

// MARK: - GetFunctionUrlConfig

/// Request for GetFunctionUrlConfig operation
@available(LambdaSwift 2.0, *)
public struct GetFunctionUrlConfigRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String

    public init(functionName: String) {
        self.functionName = functionName
    }

    public func encode(to encoder: Encoder) throws {
        _ = encoder.container(keyedBy: CodingKeys.self)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.functionName, key: "FunctionName")
    }

    private enum CodingKeys: CodingKey {}
}

/// Response for GetFunctionUrlConfig operation
@available(LambdaSwift 2.0, *)
public struct GetFunctionUrlConfigResponse: AWSDecodableShape, Sendable {
    /// The HTTP URL endpoint for the function.
    public let functionUrl: String?
    /// The type of authentication.
    public let authType: String?

    private enum CodingKeys: String, CodingKey {
        case functionUrl = "FunctionUrl"
        case authType = "AuthType"
    }
}

// MARK: - AddPermission

/// Request for AddPermission operation
@available(LambdaSwift 2.0, *)
public struct AddPermissionRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String
    /// A statement identifier that differentiates the statement from others in the same policy.
    public let statementId: String
    /// The action that the principal can use on the function.
    public let action: String
    /// The AWS service or AWS account that invokes the function.
    public let principal: String
    /// The identifier for your organization in AWS Organizations.
    public let principalOrgID: String?
    /// For AWS service principals, the ARN of the AWS resource that invokes the function.
    public let sourceArn: String?
    /// For Amazon S3 only, the AWS account ID of the bucket owner.
    public let sourceAccount: String?
    /// Specify a version or alias to add permissions to a published version of the function.
    public let qualifier: String?
    /// Only update the policy if the revision ID matches the ID that's specified.
    public let revisionId: String?
    /// The type of authentication that your function URL uses.
    public let functionUrlAuthType: FunctionUrlAuthType?

    public init(
        functionName: String,
        statementId: String,
        action: String,
        principal: String,
        principalOrgID: String? = nil,
        sourceArn: String? = nil,
        sourceAccount: String? = nil,
        qualifier: String? = nil,
        revisionId: String? = nil,
        functionUrlAuthType: FunctionUrlAuthType? = nil
    ) {
        self.functionName = functionName
        self.statementId = statementId
        self.action = action
        self.principal = principal
        self.principalOrgID = principalOrgID
        self.sourceArn = sourceArn
        self.sourceAccount = sourceAccount
        self.qualifier = qualifier
        self.revisionId = revisionId
        self.functionUrlAuthType = functionUrlAuthType
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.statementId, forKey: .statementId)
        try container.encode(self.action, forKey: .action)
        try container.encode(self.principal, forKey: .principal)
        try container.encodeIfPresent(self.principalOrgID, forKey: .principalOrgID)
        try container.encodeIfPresent(self.sourceArn, forKey: .sourceArn)
        try container.encodeIfPresent(self.sourceAccount, forKey: .sourceAccount)
        try container.encodeIfPresent(self.revisionId, forKey: .revisionId)
        try container.encodeIfPresent(self.functionUrlAuthType, forKey: .functionUrlAuthType)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.functionName, key: "FunctionName")
        if let qualifier = self.qualifier {
            requestContainer.encodeQuery(qualifier, key: "Qualifier")
        }
    }

    private enum CodingKeys: String, CodingKey {
        case statementId = "StatementId"
        case action = "Action"
        case principal = "Principal"
        case principalOrgID = "PrincipalOrgID"
        case sourceArn = "SourceArn"
        case sourceAccount = "SourceAccount"
        case revisionId = "RevisionId"
        case functionUrlAuthType = "FunctionUrlAuthType"
    }
}

/// Response for AddPermission operation
@available(LambdaSwift 2.0, *)
public struct AddPermissionResponse: AWSDecodableShape, Sendable {
    /// The permission statement that's added to the function policy.
    public let statement: String?

    private enum CodingKeys: String, CodingKey {
        case statement = "Statement"
    }
}

// MARK: - RemovePermission

/// Request for RemovePermission operation
@available(LambdaSwift 2.0, *)
public struct RemovePermissionRequest: AWSEncodableShape, Sendable {
    /// The name of the Lambda function.
    public let functionName: String
    /// Statement ID of the permission to remove.
    public let statementId: String

    public init(functionName: String, statementId: String) {
        self.functionName = functionName
        self.statementId = statementId
    }

    public func encode(to encoder: Encoder) throws {
        _ = encoder.container(keyedBy: CodingKeys.self)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.functionName, key: "FunctionName")
        requestContainer.encodePath(self.statementId, key: "StatementId")
    }

    private enum CodingKeys: CodingKey {}
}
