//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT

import SotoCore

/// Error type for AWS Lambda service
@available(LambdaSwift 2.0, *)
public struct LambdaErrorType: AWSErrorType {
    enum Code: String {
        case invalidParameterValueException = "InvalidParameterValueException"
        case resourceConflictException = "ResourceConflictException"
        case resourceNotFoundException = "ResourceNotFoundException"
        case serviceException = "ServiceException"
        case tooManyRequestsException = "TooManyRequestsException"
        case codeStorageExceededException = "CodeStorageExceededException"
        case policyLengthExceededException = "PolicyLengthExceededException"
        case preconditionFailedException = "PreconditionFailedException"
        case resourceNotReadyException = "ResourceNotReadyException"
    }

    private let error: Code
    public let context: AWSErrorContext?

    /// Initialize from error code string
    public init?(errorCode: String, context: AWSErrorContext) {
        guard let error = Code(rawValue: errorCode) else { return nil }
        self.error = error
        self.context = context
    }

    internal init(_ error: Code) {
        self.error = error
        self.context = nil
    }

    /// The error code returned by the service
    public var errorCode: String { self.error.rawValue }

    /// Human-readable description
    public var description: String {
        "\(self.error.rawValue): \(self.message ?? "")"
    }

    /// One of the parameters in the request is not valid.
    public static var invalidParameterValueException: Self { .init(.invalidParameterValueException) }
    /// The resource already exists, or another operation is in progress.
    public static var resourceConflictException: Self { .init(.resourceConflictException) }
    /// The resource specified in the request does not exist.
    public static var resourceNotFoundException: Self { .init(.resourceNotFoundException) }
    /// The AWS Lambda service encountered an internal error.
    public static var serviceException: Self { .init(.serviceException) }
    /// The request throughput limit was exceeded.
    public static var tooManyRequestsException: Self { .init(.tooManyRequestsException) }
    /// Your AWS Lambda function code size exceeded the maximum allowed size.
    public static var codeStorageExceededException: Self { .init(.codeStorageExceededException) }
    /// The permissions policy for the resource is too large.
    public static var policyLengthExceededException: Self { .init(.policyLengthExceededException) }
    /// The RevisionId provided does not match the latest RevisionId for the Lambda function or alias.
    public static var preconditionFailedException: Self { .init(.preconditionFailedException) }
    /// The function is not in a ready state.
    public static var resourceNotReadyException: Self { .init(.resourceNotReadyException) }
}
