//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh - DO NOT EDIT

@_spi(SotoInternal) import SotoCore

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

@available(LambdaSwift 2.0, *)
extension STS {
    // MARK: Enums

    // MARK: Shapes

    public struct GetCallerIdentityRequest: AWSEncodableShape {
        public init() {}
    }

    public struct GetCallerIdentityResponse: AWSDecodableShape {
        /// The Amazon Web Services account ID number of the account that owns or contains the calling entity.
        public let account: String?
        /// The Amazon Web Services ARN associated with the calling entity.
        public let arn: String?
        /// The unique identifier of the calling entity. The exact value depends on the type of entity that is making the call. The values returned are those listed in the aws:userid column in the Principal table found on the Policy Variables reference page in the IAM User Guide.
        public let userId: String?

        @inlinable
        public init(account: String? = nil, arn: String? = nil, userId: String? = nil) {
            self.account = account
            self.arn = arn
            self.userId = userId
        }

        private enum CodingKeys: String, CodingKey {
            case account = "Account"
            case arn = "Arn"
            case userId = "UserId"
        }
    }
}

// MARK: - Errors

/// Error enum for STS
@available(LambdaSwift 2.0, *)
public struct STSErrorType: AWSErrorType {
    enum Code: String {
        case expiredTokenException = "ExpiredTokenException"
        case expiredTradeInTokenException = "ExpiredTradeInTokenException"
        case idpCommunicationErrorException = "IDPCommunicationError"
        case idpRejectedClaimException = "IDPRejectedClaim"
        case invalidAuthorizationMessageException = "InvalidAuthorizationMessageException"
        case invalidIdentityTokenException = "InvalidIdentityToken"
        case jwtPayloadSizeExceededException = "JWTPayloadSizeExceededException"
        case malformedPolicyDocumentException = "MalformedPolicyDocument"
        case outboundWebIdentityFederationDisabledException = "OutboundWebIdentityFederationDisabledException"
        case packedPolicyTooLargeException = "PackedPolicyTooLarge"
        case regionDisabledException = "RegionDisabledException"
        case sessionDurationEscalationException = "SessionDurationEscalationException"
    }

    private let error: Code
    public let context: AWSErrorContext?

    /// initialize STS
    public init?(errorCode: String, context: AWSErrorContext) {
        guard let error = Code(rawValue: errorCode) else { return nil }
        self.error = error
        self.context = context
    }

    internal init(_ error: Code) {
        self.error = error
        self.context = nil
    }

    /// return error code string
    public var errorCode: String { self.error.rawValue }

    /// The web identity token that was passed is expired or is not valid. Get a new identity token from the identity provider and then retry the request.
    public static var expiredTokenException: Self { .init(.expiredTokenException) }
    /// The trade-in token provided in the request has expired and can no longer be exchanged for credentials. Request a new token and retry the operation.
    public static var expiredTradeInTokenException: Self { .init(.expiredTradeInTokenException) }
    /// The request could not be fulfilled because the identity provider (IDP) that was asked to verify the incoming identity token could not be reached. This is often a transient error caused by network conditions. Retry the request a limited number of times so that you don't exceed the request rate. If the error persists, the identity provider might be down or not responding.
    public static var idpCommunicationErrorException: Self { .init(.idpCommunicationErrorException) }
    /// The identity provider (IdP) reported that authentication failed. This might be because the claim is invalid. If this error is returned for the AssumeRoleWithWebIdentity operation, it can also mean that the claim has expired or has been explicitly revoked.
    public static var idpRejectedClaimException: Self { .init(.idpRejectedClaimException) }
    /// The error returned if the message passed to DecodeAuthorizationMessage was invalid. This can happen if the token contains invalid characters, such as line breaks, or if the message has expired.
    public static var invalidAuthorizationMessageException: Self { .init(.invalidAuthorizationMessageException) }
    /// The web identity token that was passed could not be validated by Amazon Web Services. Get a new identity token from the identity provider and then retry the request.
    public static var invalidIdentityTokenException: Self { .init(.invalidIdentityTokenException) }
    /// The requested token payload size exceeds the maximum allowed size. Reduce the number of request tags included in the GetWebIdentityToken API call to reduce the token payload size.
    public static var jwtPayloadSizeExceededException: Self { .init(.jwtPayloadSizeExceededException) }
    /// The request was rejected because the policy document was malformed. The error message describes the specific error.
    public static var malformedPolicyDocumentException: Self { .init(.malformedPolicyDocumentException) }
    /// The outbound web identity federation feature is not enabled for this account. To use this feature, you must first enable it through the Amazon Web Services Management Console or API.
    public static var outboundWebIdentityFederationDisabledException: Self {
        .init(.outboundWebIdentityFederationDisabledException)
    }
    /// The request was rejected because the total packed size of the session policies and session tags combined was too large. An Amazon Web Services conversion compresses the session policy document, session policy ARNs, and session tags into a packed binary format that has a separate limit. The error message indicates by percentage how close the policies and tags are to the upper size limit. For more information, see Passing Session Tags in STS in the IAM User Guide. You could receive this error even though you meet other defined session policy and session tag limits. For more information, see IAM and STS Entity Character Limits in the IAM User Guide.
    public static var packedPolicyTooLargeException: Self { .init(.packedPolicyTooLargeException) }
    /// STS is not activated in the requested region for the account that is being asked to generate credentials. The account administrator must use the IAM console to activate STS in that region. For more information, see Activating and Deactivating STS in an Amazon Web Services Region in the IAM User Guide.
    public static var regionDisabledException: Self { .init(.regionDisabledException) }
    /// The requested token duration would extend the session beyond its original expiration time.  You cannot use this operation to extend the lifetime of a session beyond what was granted when the session was originally created.
    public static var sessionDurationEscalationException: Self { .init(.sessionDurationEscalationException) }
}

@available(LambdaSwift 2.0, *)
extension STSErrorType: Equatable {
    public static func == (lhs: STSErrorType, rhs: STSErrorType) -> Bool {
        lhs.error == rhs.error
    }
}

@available(LambdaSwift 2.0, *)
extension STSErrorType: CustomStringConvertible {
    public var description: String {
        "\(self.error.rawValue): \(self.message ?? "")"
    }
}
