//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT
//
//===----------------------------------------------------------------------===//

import SotoCore

/// Error type for STS service operations.
@available(LambdaSwift 2.0, *)
struct STSErrorType: AWSErrorType {
    enum Code: String {
        case expiredTokenException = "ExpiredTokenException"
        case malformedPolicyDocumentException = "MalformedPolicyDocument"
        case packedPolicyTooLargeException = "PackedPolicyTooLarge"
        case regionDisabledException = "RegionDisabledException"
        case idpRejectedClaimException = "IDPRejectedClaim"
        case invalidIdentityTokenException = "InvalidIdentityToken"
        case idpCommunicationErrorException = "IDPCommunicationError"
    }

    private let error: Code
    let context: AWSErrorContext?

    /// The error code returned by STS.
    var errorCode: String { self.error.rawValue }

    init?(errorCode: String, context: AWSErrorContext) {
        guard let error = Code(rawValue: errorCode) else { return nil }
        self.error = error
        self.context = context
    }

    private init(_ error: Code) {
        self.error = error
        self.context = nil
    }

    /// The security token included in the request is expired.
    static var expiredTokenException: STSErrorType { .init(.expiredTokenException) }

    /// The request was rejected because the policy document was malformed.
    static var malformedPolicyDocumentException: STSErrorType { .init(.malformedPolicyDocumentException) }

    /// The request was rejected because the total packed size of the session policies is too large.
    static var packedPolicyTooLargeException: STSErrorType { .init(.packedPolicyTooLargeException) }

    /// STS is not activated in the requested region.
    static var regionDisabledException: STSErrorType { .init(.regionDisabledException) }

    /// The identity provider rejected the request because the identity claim is invalid.
    static var idpRejectedClaimException: STSErrorType { .init(.idpRejectedClaimException) }

    /// The web identity token is invalid or expired.
    static var invalidIdentityTokenException: STSErrorType { .init(.invalidIdentityTokenException) }

    /// The request could not be fulfilled because the identity provider (IDP) is not accessible.
    static var idpCommunicationErrorException: STSErrorType { .init(.idpCommunicationErrorException) }

    var description: String {
        "\(self.errorCode): \(self.context?.message ?? "")"
    }
}
