//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT
//
//===----------------------------------------------------------------------===//

import SotoCore

// MARK: - Input Shapes

/// Request shape for the GetCallerIdentity operation.
/// This operation requires no input parameters.
@available(LambdaSwift 2.0, *)
struct STSGetCallerIdentityRequest: AWSEncodableShape {
    init() {}
}

// MARK: - Output Shapes

/// Response shape for the GetCallerIdentity operation.
@available(LambdaSwift 2.0, *)
struct STSGetCallerIdentityResponse: AWSDecodableShape {
    /// The unique identifier of the calling entity.
    /// The exact value depends on the type of entity that is making the call.
    let userId: String?

    /// The AWS account ID number of the account that owns or contains the calling entity.
    let account: String?

    /// The AWS ARN associated with the calling entity.
    let arn: String?

    private enum CodingKeys: String, CodingKey {
        case userId = "UserId"
        case account = "Account"
        case arn = "Arn"
    }
}
