version: "3"

services:

  runtime-setup:
    image: swift-aws-lambda:al2-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-amazonlinux2"

  test:
    image: swift-aws-lambda:al2-main

  test-examples:
    image: swift-aws-lambda:al2-main

  shell:
    image: swift-aws-lambda:al2-main
