//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT

import Logging
import SotoCore

/// Client for Amazon Simple Storage Service (S3).
///
/// S3 uses the REST-XML protocol with path-style addressing.
/// Endpoint: `https://s3.<region>.amazonaws.com`
@available(LambdaSwift 2.0, *)
struct S3Client: AWSService {
    let client: AWSClient
    let config: AWSServiceConfig

    /// Initialize the S3 client.
    /// - Parameters:
    ///   - client: The AWSClient used for request signing and transport.
    ///   - region: The AWS region to send requests to.
    init(client: AWSClient, region: Region) {
        self.client = client
        self.config = AWSServiceConfig(
            region: region,
            partition: region.partition,
            serviceName: "S3",
            serviceIdentifier: "s3",
            signingName: "s3",
            serviceProtocol: .restxml,
            apiVersion: "2006-03-01",
            errorType: S3ErrorType.self
        )
    }

    /// Create a new version of the service with a patch applied.
    init(from: S3Client, patch: AWSServiceConfig.Patch) {
        self.client = from.client
        self.config = from.config.with(patch: patch)
    }

    // MARK: - Operations

    /// Creates a new S3 bucket.
    ///
    /// PUT /{Bucket}
    ///
    /// When the region is not `us-east-1`, a `CreateBucketConfiguration` XML body
    /// with the `LocationConstraint` element is included.
    ///
    /// - Parameter input: The request parameters.
    /// - Returns: The response containing the bucket location.
    @discardableResult
    func createBucket(
        _ input: CreateBucketRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> CreateBucketResponse {
        try await self.client.execute(
            operation: "CreateBucket",
            path: "/{Bucket}",
            httpMethod: .PUT,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Determines if a bucket exists and you have permission to access it.
    ///
    /// HEAD /{Bucket}
    ///
    /// Returns an empty response on success. Throws `NotFound` if the bucket
    /// does not exist or you do not have permission to access it.
    ///
    /// - Parameter input: The request parameters.
    func headBucket(_ input: HeadBucketRequest, logger: Logger = AWSClient.loggingDisabled) async throws {
        try await self.client.execute(
            operation: "HeadBucket",
            path: "/{Bucket}",
            httpMethod: .HEAD,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Adds an object to a bucket.
    ///
    /// PUT /{Bucket}/{Key+}
    ///
    /// - Parameter input: The request parameters including the object body data.
    /// - Returns: The response containing ETag and version information.
    @discardableResult
    func putObject(
        _ input: PutObjectRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> PutObjectResponse {
        try await self.client.execute(
            operation: "PutObject",
            path: "/{Bucket}/{Key+}",
            httpMethod: .PUT,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Removes an object from a bucket.
    ///
    /// DELETE /{Bucket}/{Key+}
    ///
    /// - Parameter input: The request parameters.
    /// - Returns: The response containing delete marker and version information.
    @discardableResult
    func deleteObject(
        _ input: DeleteObjectRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> DeleteObjectResponse {
        try await self.client.execute(
            operation: "DeleteObject",
            path: "/{Bucket}/{Key+}",
            httpMethod: .DELETE,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
}
