//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT

import SotoCore

/// Error type for AWS S3 service
@available(LambdaSwift 2.0, *)
struct S3ErrorType: AWSErrorType {
    enum Code: String {
        case bucketAlreadyExists = "BucketAlreadyExists"
        case bucketAlreadyOwnedByYou = "BucketAlreadyOwnedByYou"
        case noSuchBucket = "NoSuchBucket"
        case noSuchKey = "NoSuchKey"
        case notFound = "NotFound"
        case invalidBucketName = "InvalidBucketName"
        case invalidObjectState = "InvalidObjectState"
    }

    private let error: Code
    let context: AWSErrorContext?

    /// The error code returned by S3.
    var errorCode: String { self.error.rawValue }

    init?(errorCode: String, context: AWSErrorContext) {
        guard let error = Code(rawValue: errorCode) else { return nil }
        self.error = error
        self.context = context
    }

    private init(_ error: Code) {
        self.error = error
        self.context = nil
    }

    /// The requested bucket name already exists. Select a different name and try again.
    static var bucketAlreadyExists: S3ErrorType { .init(.bucketAlreadyExists) }

    /// The bucket you tried to create already exists, and you own it.
    static var bucketAlreadyOwnedByYou: S3ErrorType { .init(.bucketAlreadyOwnedByYou) }

    /// The specified bucket does not exist.
    static var noSuchBucket: S3ErrorType { .init(.noSuchBucket) }

    /// The specified key does not exist.
    static var noSuchKey: S3ErrorType { .init(.noSuchKey) }

    /// The resource was not found (used by HeadBucket/HeadObject).
    static var notFound: S3ErrorType { .init(.notFound) }

    /// The specified bucket name is not valid.
    static var invalidBucketName: S3ErrorType { .init(.invalidBucketName) }

    /// The operation is not valid for the object's storage class.
    static var invalidObjectState: S3ErrorType { .init(.invalidObjectState) }

    var description: String {
        "\(self.errorCode): \(self.context?.message ?? "")"
    }
}
