//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT

@_spi(SotoInternal) import SotoCore

// MARK: - CreateBucket

/// Configuration for the bucket location constraint.
@available(LambdaSwift 2.0, *)
struct CreateBucketConfiguration: AWSEncodableShape, Sendable {
    static let _xmlRootNodeName: String? = "CreateBucketConfiguration"
    static let _xmlNamespace: String? = "http://s3.amazonaws.com/doc/2006-03-01/"

    /// The Region where the bucket will be created. If you don't specify a Region,
    /// the bucket is created in US East (N. Virginia) Region (us-east-1).
    let locationConstraint: String?

    init(locationConstraint: String? = nil) {
        self.locationConstraint = locationConstraint
    }

    private enum CodingKeys: String, CodingKey {
        case locationConstraint = "LocationConstraint"
    }
}

/// Request for CreateBucket operation.
@available(LambdaSwift 2.0, *)
struct CreateBucketRequest: AWSEncodableShape, Sendable {
    /// The name of the bucket to create.
    let bucket: String
    /// The configuration information for the bucket, including the location constraint.
    let createBucketConfiguration: CreateBucketConfiguration?

    init(bucket: String, createBucketConfiguration: CreateBucketConfiguration? = nil) {
        self.bucket = bucket
        self.createBucketConfiguration = createBucketConfiguration
    }

    func encode(to encoder: Encoder) throws {
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.bucket, key: "Bucket")
        if let config = self.createBucketConfiguration {
            try config.encode(to: encoder)
        } else {
            _ = encoder.container(keyedBy: CodingKeys.self)
        }
    }

    private enum CodingKeys: CodingKey {}
}

/// Response for CreateBucket operation.
@available(LambdaSwift 2.0, *)
struct CreateBucketResponse: AWSDecodableShape, Sendable {
    /// The URI that identifies the bucket.
    let location: String?

    init(from decoder: Decoder) throws {
        let responseContainer = decoder.userInfo[.awsResponse]! as! ResponseDecodingContainer
        self.location = try? responseContainer.decodeHeaderIfPresent(String.self, key: "Location")
    }
}

// MARK: - HeadBucket

/// Request for HeadBucket operation.
@available(LambdaSwift 2.0, *)
struct HeadBucketRequest: AWSEncodableShape, Sendable {
    /// The bucket name.
    let bucket: String

    init(bucket: String) {
        self.bucket = bucket
    }

    func encode(to encoder: Encoder) throws {
        _ = encoder.container(keyedBy: CodingKeys.self)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.bucket, key: "Bucket")
    }

    private enum CodingKeys: CodingKey {}
}

// MARK: - PutObject

/// Request for PutObject operation.
@available(LambdaSwift 2.0, *)
struct PutObjectRequest: AWSEncodableShape, Sendable {
    static let _options: AWSShapeOptions = [.allowStreaming]

    /// The bucket name.
    let bucket: String
    /// Object key for which the PUT action was initiated.
    let key: String
    /// Object data.
    let body: AWSHTTPBody

    init(bucket: String, key: String, body: AWSHTTPBody) {
        self.bucket = bucket
        self.key = key
        self.body = body
    }

    func encode(to encoder: Encoder) throws {
        _ = encoder.container(keyedBy: CodingKeys.self)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.bucket, key: "Bucket")
        requestContainer.encodePath(self.key, key: "Key")
        try self.body.encode(to: encoder)
    }

    private enum CodingKeys: CodingKey {}
}

/// Response for PutObject operation.
@available(LambdaSwift 2.0, *)
struct PutObjectResponse: AWSDecodableShape, Sendable {
    /// Entity tag for the uploaded object.
    let eTag: String?
    /// Version of the object.
    let versionId: String?

    init(from decoder: Decoder) throws {
        let responseContainer = decoder.userInfo[.awsResponse]! as! ResponseDecodingContainer
        self.eTag = try? responseContainer.decodeHeaderIfPresent(String.self, key: "ETag")
        self.versionId = try? responseContainer.decodeHeaderIfPresent(String.self, key: "x-amz-version-id")
    }
}

// MARK: - DeleteObject

/// Request for DeleteObject operation.
@available(LambdaSwift 2.0, *)
struct DeleteObjectRequest: AWSEncodableShape, Sendable {
    /// The bucket name.
    let bucket: String
    /// Key name of the object to delete.
    let key: String
    /// The version ID used to reference a specific version of the object.
    let versionId: String?

    init(bucket: String, key: String, versionId: String? = nil) {
        self.bucket = bucket
        self.key = key
        self.versionId = versionId
    }

    func encode(to encoder: Encoder) throws {
        _ = encoder.container(keyedBy: CodingKeys.self)
        let requestContainer = encoder.userInfo[.awsRequest]! as! RequestEncodingContainer
        requestContainer.encodePath(self.bucket, key: "Bucket")
        requestContainer.encodePath(self.key, key: "Key")
        if let versionId = self.versionId {
            requestContainer.encodeQuery(versionId, key: "versionId")
        }
    }

    private enum CodingKeys: CodingKey {}
}

/// Response for DeleteObject operation.
@available(LambdaSwift 2.0, *)
struct DeleteObjectResponse: AWSDecodableShape, Sendable {
    /// Indicates whether the specified object version that was permanently deleted
    /// was a delete marker.
    let deleteMarker: Bool?
    /// Returns the version ID of the delete marker.
    let versionId: String?

    init(from decoder: Decoder) throws {
        let responseContainer = decoder.userInfo[.awsResponse]! as! ResponseDecodingContainer
        self.deleteMarker = try? responseContainer.decodeHeaderIfPresent(Bool.self, key: "x-amz-delete-marker")
        self.versionId = try? responseContainer.decodeHeaderIfPresent(String.self, key: "x-amz-version-id")
    }
}
