//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh - DO NOT EDIT

@_exported import SotoCore

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

/// Service object for interacting with AWS IAM service.
///
/// Identity and Access Management Identity and Access Management (IAM) is a web service for securely controlling  access to Amazon Web Services services. With IAM, you can centrally manage users, security credentials such as access keys, and permissions that control which Amazon Web Services resources users and  applications can access. For more information about IAM, see Identity and Access Management (IAM) and the Identity and Access Management User Guide.
@available(LambdaSwift 2.0, *)
public struct IAM: AWSService {
    // MARK: Member variables

    /// Client used for communication with AWS
    public let client: AWSClient
    /// Service configuration
    public let config: AWSServiceConfig

    // MARK: Initialization

    /// Initialize the IAM client
    /// - parameters:
    ///     - client: AWSClient used to process requests
    ///     - partition: AWS partition where service resides, standard (.aws), china (.awscn), government (.awsusgov).
    ///     - endpoint: Custom endpoint URL to use instead of standard AWS servers
    ///     - middleware: Middleware chain used to edit requests before they are sent and responses before they are decoded
    ///     - timeout: Timeout value for HTTP requests
    ///     - byteBufferAllocator: Allocator for ByteBuffers
    ///     - options: Service options
    public init(
        client: AWSClient,
        partition: AWSPartition = .aws,
        endpoint: String? = nil,
        middleware: AWSMiddlewareProtocol? = nil,
        timeout: TimeAmount? = nil,
        byteBufferAllocator: ByteBufferAllocator = ByteBufferAllocator(),
        options: AWSServiceConfig.Options = []
    ) {
        self.client = client
        self.config = AWSServiceConfig(
            region: nil,
            partition: partition,
            serviceName: "IAM",
            serviceIdentifier: "iam",
            serviceProtocol: .query,
            apiVersion: "2010-05-08",
            endpoint: endpoint,
            serviceEndpoints: Self.serviceEndpoints,
            partitionEndpoints: Self.partitionEndpoints,
            variantEndpoints: Self.variantEndpoints,
            errorType: IAMErrorType.self,
            xmlNamespace: "https://iam.amazonaws.com/doc/2010-05-08/",
            middleware: middleware,
            timeout: timeout,
            byteBufferAllocator: byteBufferAllocator,
            options: options
        )
    }

    /// custom endpoints for regions
    static var serviceEndpoints: [String: String] {
        [
            "aws-cn-global": "iam.cn-north-1.amazonaws.com.cn",
            "aws-global": "iam.amazonaws.com",
            "aws-iso-b-global": "iam.us-isob-east-1.sc2s.sgov.gov",
            "aws-iso-f-global": "iam.us-isof-south-1.csp.hci.ic.gov",
            "aws-iso-global": "iam.us-iso-east-1.c2s.ic.gov",
            "aws-us-gov-global": "iam.us-gov.amazonaws.com",
        ]
    }

    /// Default endpoint and region to use for each partition
    static var partitionEndpoints: [AWSPartition: (endpoint: String, region: SotoCore.Region)] {
        [
            .aws: (endpoint: "aws-global", region: .useast1),
            .awscn: (endpoint: "aws-cn-global", region: .cnnorth1),
            .awsiso: (endpoint: "aws-iso-global", region: .usisoeast1),
            .awsisob: (endpoint: "aws-iso-b-global", region: .usisobeast1),
            .awsisof: (endpoint: "aws-iso-f-global", region: .usisofsouth1),
            .awsusgov: (endpoint: "aws-us-gov-global", region: .usgovwest1),
        ]
    }

    /// FIPS and dualstack endpoints
    static var variantEndpoints: [EndpointVariantType: AWSServiceConfig.EndpointVariant] {
        [
            [.dualstack]: .init(endpoints: [
                "aws-global": "iam.global.api.aws"
            ]),
            [.fips]: .init(endpoints: [
                "aws-global": "iam-fips.amazonaws.com",
                "aws-us-gov-global": "iam.us-gov.amazonaws.com",
            ]),
        ]
    }

    // MARK: API Calls

    /// Attaches the specified managed policy to the specified IAM role. When you attach a managed policy to a role, the managed policy becomes part of the role's permission (access) policy.  You cannot use a managed policy as the role's trust policy. The role's trust policy is created at the same time as the role, using  CreateRole . You can update a role's trust policy using  UpdateAssumerolePolicy .  Use this operation to attach a managed policy to a role. To embed an inline policy in a role, use  PutRolePolicy . For more information about policies, see Managed policies and inline policies in the IAM User Guide. As a best practice, you can validate your IAM policies.  To learn more, see Validating IAM policies  in the IAM User Guide.
    @Sendable
    @inlinable
    public func attachRolePolicy(
        _ input: AttachRolePolicyRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        try await self.client.execute(
            operation: "AttachRolePolicy",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
    /// Attaches the specified managed policy to the specified IAM role. When you attach a managed policy to a role, the managed policy becomes part of the role's permission (access) policy.  You cannot use a managed policy as the role's trust policy. The role's trust policy is created at the same time as the role, using  CreateRole . You can update a role's trust policy using  UpdateAssumerolePolicy .  Use this operation to attach a managed policy to a role. To embed an inline policy in a role, use  PutRolePolicy . For more information about policies, see Managed policies and inline policies in the IAM User Guide. As a best practice, you can validate your IAM policies.  To learn more, see Validating IAM policies  in the IAM User Guide.
    ///
    /// Parameters:
    ///   - policyArn: The Amazon Resource Name (ARN) of the IAM policy you want to attach. For more information about ARNs, see Amazon Resource Names (ARNs) in the Amazon Web Services General Reference.
    ///   - roleName: The name (friendly name, not ARN) of the role to attach the policy to. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - logger: Logger use during operation
    @inlinable
    public func attachRolePolicy(
        policyArn: String,
        roleName: String,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        let input = AttachRolePolicyRequest(
            policyArn: policyArn,
            roleName: roleName
        )
        return try await self.attachRolePolicy(input, logger: logger)
    }

    /// Creates a new role for your Amazon Web Services account. For more information about roles, see IAM roles in the IAM User Guide. For information about quotas for role names and the number of roles you can create, see IAM and STS quotas in the IAM User Guide.
    @Sendable
    @inlinable
    public func createRole(
        _ input: CreateRoleRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> CreateRoleResponse {
        try await self.client.execute(
            operation: "CreateRole",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
    /// Creates a new role for your Amazon Web Services account. For more information about roles, see IAM roles in the IAM User Guide. For information about quotas for role names and the number of roles you can create, see IAM and STS quotas in the IAM User Guide.
    ///
    /// Parameters:
    ///   - assumeRolePolicyDocument: The trust relationship policy document that grants an entity permission to assume the role. In IAM, you must provide a JSON policy that has been converted to a string. However, for CloudFormation templates formatted in YAML, you can provide the policy in JSON or YAML format. CloudFormation always converts a YAML policy to JSON format before submitting it to IAM. The regex pattern  used to validate this parameter is a string of characters consisting of the following:   Any printable ASCII  character ranging from the space character (\u0020) through the end of the ASCII character range   The printable characters in the Basic Latin and  Latin-1 Supplement character set  (through \u00FF)   The special characters tab (\u0009), line feed (\u000A), and  carriage return (\u000D)   Upon success, the response includes the same trust policy in JSON format.
    ///   - description: A description of the role.
    ///   - maxSessionDuration: The maximum session duration (in seconds) that you want to set for the specified role. If you do not specify a value for this setting, the default value of one hour is applied. This setting can have a value from 1 hour to 12 hours. Anyone who assumes the role from the CLI or API can use the DurationSeconds API parameter or the duration-seconds CLI parameter to request a longer session. The MaxSessionDuration setting determines the maximum duration that can be requested using the DurationSeconds parameter. If users don't specify a value for the DurationSeconds parameter, their security credentials are valid for one hour by default. This applies when you use the AssumeRole* API operations or the assume-role* CLI operations but does not apply when you use those operations to create a console URL. For more information, see Using IAM roles in the IAM User Guide.
    ///   - path:  The path to the role. For more information about paths, see IAM Identifiers in the IAM User Guide. This parameter is optional. If it is not included, it defaults to a slash (/). This parameter allows (through its regex pattern) a string of characters consisting  of either a forward slash (/) by itself or a string that must begin and end with forward slashes. In addition, it can contain any ASCII character from the ! (\u0021) through the DEL character (\u007F), including  most punctuation characters, digits, and upper and lowercased letters.
    ///   - permissionsBoundary: The ARN of the managed policy that is used to set the permissions boundary for the role. A permissions boundary policy defines the maximum permissions that identity-based policies can grant to an entity, but does not grant permissions. Permissions boundaries do not define the maximum permissions that a resource-based policy can grant to an entity. To learn more, see Permissions boundaries for IAM entities in the IAM User Guide. For more information about policy types, see Policy types in the IAM User Guide.
    ///   - roleName: The name of the role to create. IAM user, group, role, and policy names must be unique within the account. Names are not distinguished by case. For example, you cannot create resources named both "MyResource" and "myresource". This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - tags: A list of tags that you want to attach to the new role. Each tag consists of a key name and an associated value. For more information about tagging, see Tagging IAM resources in the IAM User Guide.  If any one of the tags is invalid or if you exceed the allowed maximum number of tags, then the entire request  fails and the resource is not created.
    ///   - logger: Logger use during operation
    @inlinable
    public func createRole(
        assumeRolePolicyDocument: String,
        description: String? = nil,
        maxSessionDuration: Int? = nil,
        path: String? = nil,
        permissionsBoundary: String? = nil,
        roleName: String,
        tags: [Tag]? = nil,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> CreateRoleResponse {
        let input = CreateRoleRequest(
            assumeRolePolicyDocument: assumeRolePolicyDocument,
            description: description,
            maxSessionDuration: maxSessionDuration,
            path: path,
            permissionsBoundary: permissionsBoundary,
            roleName: roleName,
            tags: tags
        )
        return try await self.createRole(input, logger: logger)
    }

    /// Deletes the specified role. Unlike the Amazon Web Services Management Console, when you delete a role programmatically, you must delete the items attached to the role manually, or the deletion fails. For more information, see Deleting an IAM role. Before attempting to delete a role, remove the following attached items:    Inline policies (DeleteRolePolicy)   Attached managed policies (DetachRolePolicy)   Instance profile (RemoveRoleFromInstanceProfile)   Optional – Delete instance profile after detaching from role for resource clean up (DeleteInstanceProfile)    Make sure that you do not have any Amazon EC2 instances running with the role you are about to delete. Deleting a role or instance profile that is associated with a running instance will break any applications running on the instance.
    @Sendable
    @inlinable
    public func deleteRole(_ input: DeleteRoleRequest, logger: Logger = AWSClient.loggingDisabled) async throws {
        try await self.client.execute(
            operation: "DeleteRole",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
    /// Deletes the specified role. Unlike the Amazon Web Services Management Console, when you delete a role programmatically, you must delete the items attached to the role manually, or the deletion fails. For more information, see Deleting an IAM role. Before attempting to delete a role, remove the following attached items:    Inline policies (DeleteRolePolicy)   Attached managed policies (DetachRolePolicy)   Instance profile (RemoveRoleFromInstanceProfile)   Optional – Delete instance profile after detaching from role for resource clean up (DeleteInstanceProfile)    Make sure that you do not have any Amazon EC2 instances running with the role you are about to delete. Deleting a role or instance profile that is associated with a running instance will break any applications running on the instance.
    ///
    /// Parameters:
    ///   - roleName: The name of the role to delete. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - logger: Logger use during operation
    @inlinable
    public func deleteRole(
        roleName: String,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        let input = DeleteRoleRequest(
            roleName: roleName
        )
        return try await self.deleteRole(input, logger: logger)
    }

    /// Deletes the specified inline policy that is embedded in the specified IAM role. A role can also have managed policies attached to it. To detach a managed policy from a role, use DetachRolePolicy. For more information about policies, refer to Managed policies and inline policies in the IAM User Guide.
    @Sendable
    @inlinable
    public func deleteRolePolicy(
        _ input: DeleteRolePolicyRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        try await self.client.execute(
            operation: "DeleteRolePolicy",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
    /// Deletes the specified inline policy that is embedded in the specified IAM role. A role can also have managed policies attached to it. To detach a managed policy from a role, use DetachRolePolicy. For more information about policies, refer to Managed policies and inline policies in the IAM User Guide.
    ///
    /// Parameters:
    ///   - policyName: The name of the inline policy to delete from the specified IAM role. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - roleName: The name (friendly name, not ARN) identifying the role that the policy is embedded in. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - logger: Logger use during operation
    @inlinable
    public func deleteRolePolicy(
        policyName: String,
        roleName: String,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        let input = DeleteRolePolicyRequest(
            policyName: policyName,
            roleName: roleName
        )
        return try await self.deleteRolePolicy(input, logger: logger)
    }

    /// Removes the specified managed policy from the specified role. A role can also have inline policies embedded with it. To delete an inline policy, use DeleteRolePolicy. For information about policies, see Managed policies and inline policies in the IAM User Guide.
    @Sendable
    @inlinable
    public func detachRolePolicy(
        _ input: DetachRolePolicyRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        try await self.client.execute(
            operation: "DetachRolePolicy",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
    /// Removes the specified managed policy from the specified role. A role can also have inline policies embedded with it. To delete an inline policy, use DeleteRolePolicy. For information about policies, see Managed policies and inline policies in the IAM User Guide.
    ///
    /// Parameters:
    ///   - policyArn: The Amazon Resource Name (ARN) of the IAM policy you want to detach. For more information about ARNs, see Amazon Resource Names (ARNs) in the Amazon Web Services General Reference.
    ///   - roleName: The name (friendly name, not ARN) of the IAM role to detach the policy from. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - logger: Logger use during operation
    @inlinable
    public func detachRolePolicy(
        policyArn: String,
        roleName: String,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        let input = DetachRolePolicyRequest(
            policyArn: policyArn,
            roleName: roleName
        )
        return try await self.detachRolePolicy(input, logger: logger)
    }

    /// Retrieves information about the specified role, including the role's path, GUID, ARN, and the role's trust policy that grants permission to assume the role. For more information about roles, see IAM roles in the IAM User Guide.  Policies returned by this operation are URL-encoded compliant  with RFC 3986. You can use a URL  decoding method to convert the policy back to plain JSON text. For example, if you use Java, you  can use the decode method of the java.net.URLDecoder utility class in  the Java SDK. Other languages and SDKs provide similar functionality, and some SDKs do this decoding  automatically.
    @Sendable
    @inlinable
    public func getRole(
        _ input: GetRoleRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> GetRoleResponse {
        try await self.client.execute(
            operation: "GetRole",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
    /// Retrieves information about the specified role, including the role's path, GUID, ARN, and the role's trust policy that grants permission to assume the role. For more information about roles, see IAM roles in the IAM User Guide.  Policies returned by this operation are URL-encoded compliant  with RFC 3986. You can use a URL  decoding method to convert the policy back to plain JSON text. For example, if you use Java, you  can use the decode method of the java.net.URLDecoder utility class in  the Java SDK. Other languages and SDKs provide similar functionality, and some SDKs do this decoding  automatically.
    ///
    /// Parameters:
    ///   - roleName: The name of the IAM role to get information about. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - logger: Logger use during operation
    @inlinable
    public func getRole(
        roleName: String,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> GetRoleResponse {
        let input = GetRoleRequest(
            roleName: roleName
        )
        return try await self.getRole(input, logger: logger)
    }

    /// Adds or updates an inline policy document that is embedded in the specified IAM role. When you embed an inline policy in a role, the inline policy is used as part of the role's access (permissions) policy. The role's trust policy is created at the same time as the role, using  CreateRole . You can update a role's trust policy using  UpdateAssumeRolePolicy . For more information about roles, see IAM roles in the IAM User Guide. A role can also have a managed policy attached to it. To attach a managed policy to a role, use  AttachRolePolicy . To create a new managed policy, use  CreatePolicy . For information about policies, see Managed policies and inline policies in the IAM User Guide. For information about the maximum number of inline policies that you can embed with a role, see IAM and STS quotas in the IAM User Guide.  Because policy documents can be large, you should use POST rather than GET when calling PutRolePolicy. For general information about using the Query API with IAM, see Making query requests in the IAM User Guide.
    @Sendable
    @inlinable
    public func putRolePolicy(_ input: PutRolePolicyRequest, logger: Logger = AWSClient.loggingDisabled) async throws {
        try await self.client.execute(
            operation: "PutRolePolicy",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
    /// Adds or updates an inline policy document that is embedded in the specified IAM role. When you embed an inline policy in a role, the inline policy is used as part of the role's access (permissions) policy. The role's trust policy is created at the same time as the role, using  CreateRole . You can update a role's trust policy using  UpdateAssumeRolePolicy . For more information about roles, see IAM roles in the IAM User Guide. A role can also have a managed policy attached to it. To attach a managed policy to a role, use  AttachRolePolicy . To create a new managed policy, use  CreatePolicy . For information about policies, see Managed policies and inline policies in the IAM User Guide. For information about the maximum number of inline policies that you can embed with a role, see IAM and STS quotas in the IAM User Guide.  Because policy documents can be large, you should use POST rather than GET when calling PutRolePolicy. For general information about using the Query API with IAM, see Making query requests in the IAM User Guide.
    ///
    /// Parameters:
    ///   - policyDocument: The policy document. You must provide policies in JSON format in IAM. However, for CloudFormation templates formatted in YAML, you can provide the policy in JSON or YAML format. CloudFormation always converts a YAML policy to JSON format before submitting it to IAM. The regex pattern  used to validate this parameter is a string of characters consisting of the following:   Any printable ASCII  character ranging from the space character (\u0020) through the end of the ASCII character range   The printable characters in the Basic Latin and  Latin-1 Supplement character set  (through \u00FF)   The special characters tab (\u0009), line feed (\u000A), and  carriage return (\u000D)
    ///   - policyName: The name of the policy document. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - roleName: The name of the role to associate the policy with. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - logger: Logger use during operation
    @inlinable
    public func putRolePolicy(
        policyDocument: String,
        policyName: String,
        roleName: String,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        let input = PutRolePolicyRequest(
            policyDocument: policyDocument,
            policyName: policyName,
            roleName: roleName
        )
        return try await self.putRolePolicy(input, logger: logger)
    }
}

@available(LambdaSwift 2.0, *)
extension IAM {
    /// Initializer required by `AWSService.with(middlewares:timeout:byteBufferAllocator:options)`. You are not able to use this initializer directly as there are not public
    /// initializers for `AWSServiceConfig.Patch`. Please use `AWSService.with(middlewares:timeout:byteBufferAllocator:options)` instead.
    public init(from: IAM, patch: AWSServiceConfig.Patch) {
        self.client = from.client
        self.config = from.config.with(patch: patch)
    }
}

// MARK: Waiters

@available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
@available(LambdaSwift 2.0, *)
extension IAM {
    /// Waiter for operation ``getRole(_:logger:)``.
    ///
    /// - Parameters:
    ///   - input: Input for operation
    ///   - logger: Logger used for logging
    @inlinable
    public func waitUntilRoleExists(
        _ input: GetRoleRequest,
        maxWaitTime: TimeAmount? = nil,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        let waiter = AWSClient.Waiter<GetRoleRequest, _>(
            acceptors: [
                .init(state: .success, matcher: AWSSuccessMatcher()),
                .init(state: .retry, matcher: AWSErrorCodeMatcher("NoSuchEntity")),
            ],
            minDelayTime: .seconds(1),
            command: self.getRole
        )
        return try await self.client.waitUntil(input, waiter: waiter, maxWaitTime: maxWaitTime, logger: logger)
    }
    /// Waiter for operation ``getRole(_:logger:)``.
    ///
    /// - Parameters:
    ///   - roleName: The name of the IAM role to get information about. This parameter allows (through its regex pattern) a string of characters consisting of upper and lowercase alphanumeric  characters with no spaces. You can also include any of the following characters: _+=,.@-
    ///   - logger: Logger used for logging
    @inlinable
    public func waitUntilRoleExists(
        roleName: String,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        let input = GetRoleRequest(
            roleName: roleName
        )
        try await self.waitUntilRoleExists(input, logger: logger)
    }
}
