//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT

import Logging
import SotoCore

/// AWS Identity and Access Management (IAM) service client.
///
/// IAM uses the AWS Query protocol. The endpoint is global:
/// `https://iam.amazonaws.com`
///
/// Operations use POST with `Action=<operation>&Version=2010-05-08`
/// URL-encoded form body. Responses are XML.
@available(LambdaSwift 2.0, *)
public struct IAMClient: AWSService {
    /// The underlying AWS client used for making requests.
    public let client: AWSClient
    /// The AWS region where requests are sent.
    public let region: Region
    /// Service configuration for AWS IAM.
    public let config: AWSServiceConfig

    /// Initialize an IAM client.
    /// - Parameters:
    ///   - client: The AWSClient to use for requests.
    ///   - region: The AWS region to target (IAM is global, defaults to us-east-1).
    public init(client: AWSClient, region: Region = .useast1) {
        self.client = client
        self.region = region
        self.config = AWSServiceConfig(
            region: .useast1,
            partition: .aws,
            serviceName: "IAM",
            serviceIdentifier: "iam",
            signingName: "iam",
            serviceProtocol: .query,
            apiVersion: "2010-05-08",
            endpoint: "https://iam.amazonaws.com",
            errorType: IAMErrorType.self
        )
    }

    /// Create a new version of the service with a patch applied.
    public init(from: IAMClient, patch: AWSServiceConfig.Patch) {
        self.client = from.client
        self.region = from.region
        self.config = from.config.with(patch: patch)
    }

    // MARK: - Operations

    /// Creates a new IAM role.
    /// - Parameter input: The request parameters.
    /// - Returns: The newly created role.
    @discardableResult
    public func createRole(
        _ input: IAMCreateRoleRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> IAMCreateRoleResponse {
        try await self.client.execute(
            operation: "CreateRole",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Deletes the specified IAM role.
    /// - Parameter input: The request parameters.
    public func deleteRole(_ input: IAMDeleteRoleRequest, logger: Logger = AWSClient.loggingDisabled) async throws {
        try await self.client.execute(
            operation: "DeleteRole",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Retrieves information about the specified IAM role.
    /// - Parameter input: The request parameters.
    /// - Returns: The role details.
    @discardableResult
    public func getRole(
        _ input: IAMGetRoleRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws -> IAMGetRoleResponse {
        try await self.client.execute(
            operation: "GetRole",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Attaches the specified managed policy to the specified IAM role.
    /// - Parameter input: The request parameters.
    public func attachRolePolicy(
        _ input: IAMAttachRolePolicyRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        try await self.client.execute(
            operation: "AttachRolePolicy",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Removes the specified managed policy from the specified IAM role.
    /// - Parameter input: The request parameters.
    public func detachRolePolicy(
        _ input: IAMDetachRolePolicyRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        try await self.client.execute(
            operation: "DetachRolePolicy",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Adds or updates an inline policy document that is embedded in the specified IAM role.
    /// - Parameter input: The request parameters.
    public func putRolePolicy(_ input: IAMPutRolePolicyRequest, logger: Logger = AWSClient.loggingDisabled) async throws
    {
        try await self.client.execute(
            operation: "PutRolePolicy",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }

    /// Deletes the specified inline policy from the specified IAM role.
    /// - Parameter input: The request parameters.
    public func deleteRolePolicy(
        _ input: IAMDeleteRolePolicyRequest,
        logger: Logger = AWSClient.loggingDisabled
    ) async throws {
        try await self.client.execute(
            operation: "DeleteRolePolicy",
            path: "/",
            httpMethod: .POST,
            serviceConfig: self.config,
            input: input,
            logger: logger
        )
    }
}
