//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT

import SotoCore

/// Error type for AWS IAM service operations.
@available(LambdaSwift 2.0, *)
public struct IAMErrorType: AWSErrorType {
    enum Code: String {
        case entityAlreadyExistsException = "EntityAlreadyExists"
        case entityTemporarilyUnmodifiableException = "EntityTemporarilyUnmodifiable"
        case invalidInputException = "InvalidInput"
        case limitExceededException = "LimitExceeded"
        case malformedPolicyDocumentException = "MalformedPolicyDocument"
        case noSuchEntityException = "NoSuchEntity"
        case deleteConflictException = "DeleteConflict"
        case serviceFailureException = "ServiceFailure"
        case unmodifiableEntityException = "UnmodifiableEntity"
        case policyNotAttachableException = "PolicyNotAttachable"
    }

    private let error: Code
    public let context: AWSErrorContext?

    /// The error code returned by IAM.
    public var errorCode: String { self.error.rawValue }

    /// Initialize from error code string.
    public init?(errorCode: String, context: AWSErrorContext) {
        guard let error = Code(rawValue: errorCode) else { return nil }
        self.error = error
        self.context = context
    }

    internal init(_ error: Code) {
        self.error = error
        self.context = nil
    }

    /// Human-readable description.
    public var description: String {
        "\(self.error.rawValue): \(self.message ?? "")"
    }

    /// The request was rejected because it attempted to create a resource that already exists.
    public static var entityAlreadyExistsException: Self { .init(.entityAlreadyExistsException) }

    /// The request was rejected because the entity is temporarily unmodifiable.
    public static var entityTemporarilyUnmodifiableException: Self { .init(.entityTemporarilyUnmodifiableException) }

    /// The request was rejected because an invalid or out-of-range value was supplied for an input parameter.
    public static var invalidInputException: Self { .init(.invalidInputException) }

    /// The request was rejected because it attempted to create resources beyond the current AWS account limits.
    public static var limitExceededException: Self { .init(.limitExceededException) }

    /// The request was rejected because the policy document was malformed.
    public static var malformedPolicyDocumentException: Self { .init(.malformedPolicyDocumentException) }

    /// The request was rejected because it referenced a resource entity that does not exist.
    public static var noSuchEntityException: Self { .init(.noSuchEntityException) }

    /// The request was rejected because it attempted to delete a resource that has attached subordinate entities.
    public static var deleteConflictException: Self { .init(.deleteConflictException) }

    /// The request processing has failed because of an unknown error, exception, or failure.
    public static var serviceFailureException: Self { .init(.serviceFailureException) }

    /// The request was rejected because only the service that depends on the service-linked role can modify or delete the role.
    public static var unmodifiableEntityException: Self { .init(.unmodifiableEntityException) }

    /// The request failed because the provided policy is not attachable.
    public static var policyNotAttachableException: Self { .init(.policyNotAttachableException) }
}
