//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftAWSLambdaRuntime open source project
//
// Copyright SwiftAWSLambdaRuntime project authors
// Copyright (c) Amazon.com, Inc. or its affiliates.
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftAWSLambdaRuntime project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by scripts/generate-aws-clients.sh — DO NOT EDIT

import SotoCore

// MARK: - Common Shapes

/// Represents an IAM role.
@available(LambdaSwift 2.0, *)
public struct IAMRole: AWSDecodableShape, Sendable {
    /// The friendly name that identifies the role.
    public let roleName: String?
    /// The stable and unique string identifying the role.
    public let roleId: String?
    /// The Amazon Resource Name (ARN) specifying the role.
    public let arn: String?
    /// The path to the role.
    public let path: String?
    /// The date and time when the role was created.
    public let createDate: String?
    /// The policy document that grants an entity permission to assume the role.
    public let assumeRolePolicyDocument: String?
    /// A description of the role.
    public let description: String?

    private enum CodingKeys: String, CodingKey {
        case roleName = "RoleName"
        case roleId = "RoleId"
        case arn = "Arn"
        case path = "Path"
        case createDate = "CreateDate"
        case assumeRolePolicyDocument = "AssumeRolePolicyDocument"
        case description = "Description"
    }
}

// MARK: - CreateRole

/// Request for the CreateRole operation.
@available(LambdaSwift 2.0, *)
public struct IAMCreateRoleRequest: AWSEncodableShape, Sendable {
    /// The name of the role to create.
    public let roleName: String
    /// The trust relationship policy document that grants an entity permission to assume the role.
    public let assumeRolePolicyDocument: String
    /// The path to the role.
    public let path: String?
    /// A description of the role.
    public let description: String?

    public init(
        roleName: String,
        assumeRolePolicyDocument: String,
        path: String? = nil,
        description: String? = nil
    ) {
        self.roleName = roleName
        self.assumeRolePolicyDocument = assumeRolePolicyDocument
        self.path = path
        self.description = description
    }

    private enum CodingKeys: String, CodingKey {
        case roleName = "RoleName"
        case assumeRolePolicyDocument = "AssumeRolePolicyDocument"
        case path = "Path"
        case description = "Description"
    }
}

/// Response for the CreateRole operation.
@available(LambdaSwift 2.0, *)
public struct IAMCreateRoleResponse: AWSDecodableShape, Sendable {
    /// The role that was created.
    public let role: IAMRole?

    private enum CodingKeys: String, CodingKey {
        case role = "Role"
    }
}

// MARK: - DeleteRole

/// Request for the DeleteRole operation.
@available(LambdaSwift 2.0, *)
public struct IAMDeleteRoleRequest: AWSEncodableShape, Sendable {
    /// The name of the role to delete.
    public let roleName: String

    public init(roleName: String) {
        self.roleName = roleName
    }

    private enum CodingKeys: String, CodingKey {
        case roleName = "RoleName"
    }
}

// MARK: - GetRole

/// Request for the GetRole operation.
@available(LambdaSwift 2.0, *)
public struct IAMGetRoleRequest: AWSEncodableShape, Sendable {
    /// The name of the IAM role to get information about.
    public let roleName: String

    public init(roleName: String) {
        self.roleName = roleName
    }

    private enum CodingKeys: String, CodingKey {
        case roleName = "RoleName"
    }
}

/// Response for the GetRole operation.
@available(LambdaSwift 2.0, *)
public struct IAMGetRoleResponse: AWSDecodableShape, Sendable {
    /// The role details.
    public let role: IAMRole?

    private enum CodingKeys: String, CodingKey {
        case role = "Role"
    }
}

// MARK: - AttachRolePolicy

/// Request for the AttachRolePolicy operation.
@available(LambdaSwift 2.0, *)
public struct IAMAttachRolePolicyRequest: AWSEncodableShape, Sendable {
    /// The name of the IAM role to attach the policy to.
    public let roleName: String
    /// The Amazon Resource Name (ARN) of the IAM policy to attach.
    public let policyArn: String

    public init(roleName: String, policyArn: String) {
        self.roleName = roleName
        self.policyArn = policyArn
    }

    private enum CodingKeys: String, CodingKey {
        case roleName = "RoleName"
        case policyArn = "PolicyArn"
    }
}

// MARK: - DetachRolePolicy

/// Request for the DetachRolePolicy operation.
@available(LambdaSwift 2.0, *)
public struct IAMDetachRolePolicyRequest: AWSEncodableShape, Sendable {
    /// The name of the IAM role to detach the policy from.
    public let roleName: String
    /// The Amazon Resource Name (ARN) of the IAM policy to detach.
    public let policyArn: String

    public init(roleName: String, policyArn: String) {
        self.roleName = roleName
        self.policyArn = policyArn
    }

    private enum CodingKeys: String, CodingKey {
        case roleName = "RoleName"
        case policyArn = "PolicyArn"
    }
}

// MARK: - PutRolePolicy

/// Request for the PutRolePolicy operation.
@available(LambdaSwift 2.0, *)
public struct IAMPutRolePolicyRequest: AWSEncodableShape, Sendable {
    /// The name of the role to associate the policy with.
    public let roleName: String
    /// The name of the policy document.
    public let policyName: String
    /// The policy document (JSON string).
    public let policyDocument: String

    public init(roleName: String, policyName: String, policyDocument: String) {
        self.roleName = roleName
        self.policyName = policyName
        self.policyDocument = policyDocument
    }

    private enum CodingKeys: String, CodingKey {
        case roleName = "RoleName"
        case policyName = "PolicyName"
        case policyDocument = "PolicyDocument"
    }
}

// MARK: - DeleteRolePolicy

/// Request for the DeleteRolePolicy operation.
@available(LambdaSwift 2.0, *)
public struct IAMDeleteRolePolicyRequest: AWSEncodableShape, Sendable {
    /// The name of the role the policy is associated with.
    public let roleName: String
    /// The name of the inline policy to delete.
    public let policyName: String

    public init(roleName: String, policyName: String) {
        self.roleName = roleName
        self.policyName = policyName
    }

    private enum CodingKeys: String, CodingKey {
        case roleName = "RoleName"
        case policyName = "PolicyName"
    }
}
